"""followers

Revision ID: 54235ee70e82
Revises: 0c5fe49e67db
Create Date: 2020-05-23 21:47:08.365703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54235ee70e82'
down_revision = '0c5fe49e67db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
